### ISSUE TITLE
No active pull requests shown

### ISSUE THREAD

**Issue by jmezach** [sierpinski/Blitz#17]
We just installed this extension on our on-premise TFS 2015 Update 3 server but we don't see any active pull requests even though we're sure there are some. Opening the Chrome developer tools displays the following errors:

```
appinsightsblitz.js:2 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.(…)window.appInsights.config.instrumentationKey @ appinsightsblitz.js:2(anonymous function) @ appinsightsblitz.js:3
2jquery-2.2.3.min.js:4 OPTIONS https://tfs.rhea.infosupport.net/TFS/NS/NS%20Railpocket/_apis/git/PullRequests send @ jquery-2.2.3.min.js:4ajax @ jquery-2.2.3.min.js:4(anonymous function) @ corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64n._wrapCallback @ VSS.SDK.min.js:4(anonymous function) @ VSS.SDK.min.js:4(anonymous function) @ VSS.SDK.min.js:4
blitzallpulls.html:1 XMLHttpRequest cannot load https://tfs.rhea.infosupport.net/TFS/NS/NS%20Railpocket/_apis/git/PullRequests. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 440.
q.js:27 Error: An undefined error occurred while attempting to connect to the server. Status code 0: error.(…)
```

Any ideas?

**Comment by sierpinski** [comment]
Thanks for the info. I haven't seen this particular error, though on-premises deployments had previously had some difficulties with the extension.. I believe it would be caused by my extension inside the iframe hosted by TFS, which is effectively sandboxed, sending an Ajax request to your TFS system and failing because it is unauthenticated.

The 440 HTTP response may mean there was some kind of timeout error during authentication. Are you still experiencing this problem now? If so, this will take a bit of investigating.

**Comment by jmezach** [comment]
Hmm, could this have something to do with the Forefront TMG that's in front of our TFS server perhaps?

**Comment by sierpinski** [comment]
I haven't heard about that issue so I can't say if it is or isn't related.

**Comment by jmezach** [comment]
I was in the office last Friday so I didn't have to go through the Forefront TMG and the extension worked perfectly so its definitely related. My guess is that other extension would have the same problem though. I'll try to see what we can do on our end.

**Comment by ptoonen** [comment]
This issue seems to be that the gitClient doesn't send a cookie nor origin-header when making requests on https://github.com/sierpinski/Blitz/blob/master/scripts/blitzallpulls.js#L24.
This doesn't seem to be an issue with the plugin but rather the rest client provided by TFS.

Possibly related to https://github.com/sierpinski/Blitz/issues/13

**Comment by ptoonen** [comment]
Verified the hypotheses by injecting the cookie and origin-header with Fiddler.

**Comment by sierpinski** [comment]
Thank you this is great detective work. [Possibly related issue.](https://github.com/sierpinski/Blitz/issues/16) The team in that issue temporarily resolved the matter by having team members access the TFS server by machine name in the url. That work-around is not ideal. The best step for me now is to open an issue with the VSTS team and see if they can make progress.
