### ISSUE TITLE
Make UI consistent with TFS/VSTS

### ISSUE THREAD

**Issue by J-Sek** [sierpinski/Blitz#21]
If I understand correctly, the ultimate goal of this project is to do what "Pull Requests" tab is already doing, only better (by ignoring current repository scope). As a user I expect to see the same controls for Pull Requests.

What bothers me right now is the fact that content of the new tab looks totally different from what all users are used to see in "Pull Requests" tab. It makes new users confused and not willing to interact with the extension.

**Comment by sierpinski** [comment]
Thanks for creating an issue for this. When I first made my extension, there were pretty limited options for matching the UI around the rest of the app so I chose bootstrap because it was fast. If I get a chance, I can look into the options MS exposes. It might not be too difficult to pull off. I'll let you know if/when I can take a look and get some feedback from you as I do.

**Comment by J-Sek** [comment]
I don't think it is any better now. Just by looking at Microsoft documentation, I would not choose their API to create view with list of pull requests. It did not work well for [Active Pull Requests](https://marketplace.visualstudio.com/items?itemName=mimeo.mimeo-active-pull-requests).

If you are interested in having UI matching TFS/VSTS I suggest creating view templates based mostly on what you can see on "Pull Requests" page.
I have done it for [my own extension](https://gitlab.com/jsek-chrome/tfs-all-my-pull-requests) (for Google Chrome). It is simple, but the cost is that I will be forced to change the view in case Microsoft decides to do redesign or perfoms significant changes to CSS.

**Comment by karlingen** [comment]
@J-Sek Check out this one: https://marketplace.visualstudio.com/items?itemName=karlingen.active-pull-requests&ssr=false#overview
